# Example file for controlling loading image and overlay text display
# To activate remove "_example" from filename
# ---------------------------------------------------------------------------------------
# Note: Specify filenames without extension (.jpg will be added internally)
# ---------------------------------------------------------------------------------------

# Overlay title
Title: <b><#00ffff>Reforged Eden 2 Beta</color></b> <size=65%><#ffffff>(build 15)</color></size>

# Overlay body (typically multi-line text)
# If commented out, only the title will be displayed
Body: |
  <size=135%><#ffffff><b>June 25:</b></color></size>
  <size=85%><b>Welcome to beta! The scenario should be stable enough for a proper survival play through or creative use in singleplayer and multiplayer.</b></size>
  <size=85%>•<indent=3%>Updated Rados Foundry found on lava and hell class planets.</indent></size>
  <size=85%>•<indent=3%>Added new decorative cables to ship deco blocks.</indent></size>
  <size=85%>•<indent=3%>Added new trap blocks for POI use.</indent></size>
  <size=85%>•<indent=3%>Misc fixes. See Change Notes on the Workshop for details.</indent></size>
  
  <size=85%><#ffffff>REMINDER: You can adjust enemy difficulty in your difficulty settings to change NPC health and damage scaling.</size>
  <size=85%><#ffff00>Reforged Eden 2 is currently in Beta. You may encounter bugs and other problems while playing. Please leave feedback on the workshop and report any issues you encounter on GitHub.</size>
  
# To show a certain image at the start of each loading image sequence, specify the respective file name
# To use the default random image selection, comment out the following line
# FirstPic: p49

# To show the overlay text with certain images only, specify the respective file names
# To show the text with every image, comment out the following line
# ShowWith: [ p02, p03 ]

# Show time for images - if not specified differently below
# If commented out, the default is 10 seconds
# Note: This time depends on the speed of the client computer as when loading a game a lot of work is done in parallel
StandardShowTime: 20

# To set a specific show time for certain images, specify "filename: time" lines
# If not needed, comment out all lines of the following parameter
# ShowTimes:
  # p49: 45
  # p06: 8
