# Example file for controlling loading image and overlay text display
# To activate remove "_example" from filename
# ---------------------------------------------------------------------------------------
# Note: Specify filenames without extension (.jpg will be added internally)
# ---------------------------------------------------------------------------------------

# Overlay title
Title: <b><#00ffff>Reforged Eden 2 Beta</color></b> <size=65%><#ffffff>(build 18)</color></size>

# Overlay body (typically multi-line text)
# If commented out, only the title will be displayed
Body: |
  <size=135%><#ffffff><b>July 22:</b></color></size>
  <size=85%>•<indent=3%>Multitool turrets have a built in drill mode now, combining the function of both the multitool and drill turret into one.</indent></size>
  <size=85%>•<indent=3%>Adjusted CPU scaling for medium and heavy weapons.</indent></size>
  <size=85%>•<indent=3%>Greatly increased durability of player armor to help offset protection being reduced by durability damage.</indent></size>
  <size=85%>•<indent=3%>Added SV Flare Launcher (Experimental). They launch flares behind your ship that will block rockets and interfere with turret tracking for a few seconds.</indent></size>
  <size=85%>•<indent=3%>Added consoles to abandoned POIs that give info on the POI itself and recommended equipment.</indent></size>
  <size=85%>•<indent=3%>Added markers to asteroid fields to more easily find resource asteroids.</indent></size>
  <size=85%>•<indent=3%>Updated Trade Federation space Trading Station Olivine.</indent></size>
  <size=85%>•<indent=3%>Added mining contracts to Polaris Orbital Refineries.</indent></size>
  <size=85%>•<indent=3%>Added new holographic advertisements and a new holo screen.</indent></size>
  <size=85%>•<indent=3%>Misc other changes and fixes.</indent></size>
  <size=85%><#ffff00>Reforged Eden 2 is currently in Beta. You may encounter bugs and other problems while playing. Please leave feedback on the workshop and report any issues you encounter on GitHub.</size>
  
# To show a certain image at the start of each loading image sequence, specify the respective file name
# To use the default random image selection, comment out the following line
# FirstPic: p49

# To show the overlay text with certain images only, specify the respective file names
# To show the text with every image, comment out the following line
# ShowWith: [ p02, p03 ]

# Show time for images - if not specified differently below
# If commented out, the default is 10 seconds
# Note: This time depends on the speed of the client computer as when loading a game a lot of work is done in parallel
StandardShowTime: 20

# To set a specific show time for certain images, specify "filename: time" lines
# If not needed, comment out all lines of the following parameter
# ShowTimes:
  # p49: 45
  # p06: 8
